ARG CASSANDRA_VERSION=3.11.9

FROM --platform=$BUILDPLATFORM maven:3.6.3-jdk-8-slim as builder

ARG METRICS_COLLECTOR_VERSION=0.2.0

WORKDIR /build

COPY pom.xml ./
COPY management-api-agent-common/pom.xml ./management-api-agent-common/pom.xml
COPY management-api-agent-3.x/pom.xml ./management-api-agent-3.x/pom.xml
COPY management-api-agent-4.x/pom.xml ./management-api-agent-4.x/pom.xml
COPY management-api-common/pom.xml ./management-api-common/pom.xml
COPY management-api-server/pom.xml ./management-api-server/pom.xml
# this duplicates work done in the next steps, but this should provide
# a solid cache layer that only gets reset on pom.xml changes
RUN mvn -q -ff -T 1C install -DskipTests && rm -rf target

COPY management-api-agent-common ./management-api-agent-common
COPY management-api-agent-3.x ./management-api-agent-3.x
COPY management-api-agent-4.x ./management-api-agent-4.x
COPY management-api-common ./management-api-common
COPY management-api-server ./management-api-server
RUN mvn -q -ff package -DskipTests

# Download and extract Metrics Collector
ENV MCAC_PATH /opt/metrics-collector
RUN mkdir ${MCAC_PATH} && \
    if test ! -e datastax-mcac-agent-${METRICS_COLLECTOR_VERSION}.tar.gz; then curl -L -O "https://github.com/datastax/metric-collector-for-apache-cassandra/releases/download/v${METRICS_COLLECTOR_VERSION}/datastax-mcac-agent-${METRICS_COLLECTOR_VERSION}.tar.gz"; fi && \
    tar --directory ${MCAC_PATH} --strip-components 1 --gzip --extract --file datastax-mcac-agent-${METRICS_COLLECTOR_VERSION}.tar.gz

# Netty arm64 epoll support was not added until 4.1.50 (https://github.com/netty/netty/pull/9804)
# Only replace this dependency for arm64 to avoid regressions

# Update some libraries that ship with Cassandra 3.11 to address some CVEs
RUN mvn dependency:get -q -DgroupId=io.netty -DartifactId=netty-all -Dversion=4.1.51.Final -Dtransitive=false
# Get updated logback libs
RUN mvn dependency:get -q -DgroupId=ch.qos.logback -DartifactId=logback-classic -Dversion=1.2.3 -Dtransitive=false
RUN mvn dependency:get -q -DgroupId=ch.qos.logback -DartifactId=logback-core -Dversion=1.2.3 -Dtransitive=false
# Get updated Jackson libs
RUN mvn dependency:get -q -DgroupId=com.fasterxml.jackson.core -DartifactId=jackson-annotations -Dversion=2.11.1 -Dtransitive=false
RUN mvn dependency:get -q -DgroupId=com.fasterxml.jackson.core -DartifactId=jackson-core -Dversion=2.11.1 -Dtransitive=false
RUN mvn dependency:get -q -DgroupId=com.fasterxml.jackson.core -DartifactId=jackson-databind -Dversion=2.11.1 -Dtransitive=false

FROM --platform=$BUILDPLATFORM cassandra:${CASSANDRA_VERSION} as oss311

ARG TARGETARCH

ENV CASSANDRA_PATH /opt/cassandra
ENV MAAC_PATH /opt/management-api
ENV MCAC_PATH /opt/metrics-collector

ENV CASSANDRA_HOME ${CASSANDRA_PATH}
ENV CASSANDRA_CONF ${CASSANDRA_PATH}/conf
ENV CASSANDRA_LOGS ${CASSANDRA_PATH}/logs
# Log directory for Management API startup logs to avoid issues:
# https://datastax.jira.com/browse/DB-4627
# https://issues.apache.org/jira/browse/CASSANDRA-16027
ENV MGMT_API_LOG_DIR /var/log/cassandra

COPY --from=builder /build/management-api-agent-3.x/target/datastax-mgmtapi-agent-3.x-0.1.0-SNAPSHOT.jar ${MAAC_PATH}/datastax-mgmtapi-agent-0.1.0-SNAPSHOT.jar
COPY --from=builder /build/management-api-server/target/datastax-mgmtapi-server-0.1.0-SNAPSHOT.jar ${MAAC_PATH}/
COPY --from=builder ${MCAC_PATH} ${MCAC_PATH}
# Update netty-all
RUN rm ${CASSANDRA_PATH}/lib/netty-all-*.jar
COPY --from=builder /root/.m2/repository/io/netty/netty-all/4.1.51.Final/netty-all-4.1.51.Final.jar ${CASSANDRA_PATH}/lib/netty-all-4.1.51.Final.jar
# Update logback libs
RUN rm ${CASSANDRA_PATH}/lib/logback-*.jar
COPY --from=builder /root/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar ${CASSANDRA_PATH}/lib/logback-classic-1.2.3.jar
COPY --from=builder /root/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar ${CASSANDRA_PATH}/lib/logback-core-1.2.3.jar
# Update Jackson libs
RUN rm ${CASSANDRA_PATH}/lib/jackson-*.jar
COPY --from=builder /root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.1/jackson-annotations-2.11.1.jar ${CASSANDRA_PATH}/lib/jackson-annotations-2.11.1.jar
COPY --from=builder /root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.1/jackson-core-2.11.1.jar ${CASSANDRA_PATH}/lib/jackson-core-2.11.1.jar
COPY --from=builder /root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.1/jackson-databind-2.11.1.jar ${CASSANDRA_PATH}/lib/jackson-databind-2.11.1.jar

# Setup user and fixup permissions
RUN chown -R cassandra:cassandra ${CASSANDRA_PATH} ${MAAC_PATH} ${MCAC_PATH} && \
    chmod -R g+w ${CASSANDRA_PATH} ${MAAC_PATH} ${MCAC_PATH}

ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} /tini
RUN chmod +x /tini

RUN set -eux; \
  rm -fr /etc/apt/sources.list.d/*; \
  rm -rf /var/lib/apt/lists/*; \
  apt-get update; \
  apt-get install -y --no-install-recommends wget iproute2; \
  rm -rf /var/lib/apt/lists/*

# backwards compat with upstream ENTRYPOINT
COPY scripts/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
  ln -sf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 9103
EXPOSE 8080

USER cassandra

ENTRYPOINT ["/tini", "-g", "--", "/docker-entrypoint.sh"]
CMD ["mgmtapi"]
