name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    types: [opened, reopened]

jobs:
  run-unit-tests:
    name: Run Unit tests
    runs-on: macos-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v6
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-hcd-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Maven settings file
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>artifactory-snapshots</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
              </server>
              <server>
                <id>artifactory-releases</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
              </server>
              <server>
                <id>artifactory</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF
      - name: Build with Maven and run unit tests (k8ssandra repo)
        if: github.repository_owner == 'k8ssandra'
        run: mvn -B -q package --file pom.xml -P dse,hcd
      - name: Build with Maven and run unit tests (3rd party repo)
        if: github.repository_owner != 'k8ssandra'
        run: mvn -B -q package --file pom.xml
      - name: Save Maven cache
        uses: actions/cache/save@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ github.sha }}-${{ hashFiles('**/pom.xml') }}
      - name: Save Maven build artifacts
        uses: actions/cache/save@v5
        with:
          path: /home/runner/work/management-api-for-apache-cassandra/management-api-for-apache-cassandra
          key: ${{ runner.os }}-workspace-${{ github.sha }}-${{ hashFiles('**/pom.xml') }}
      - name: Save Cassandra Download for tests
        uses: actions/cache/save@v5
        with:
          path: /home/runner/work/management-api-for-apache-cassandra/management-api-for-apache-cassandra/management-api-server/.cassandra-bin
          key: cassandra-download-${{ github.sha }}
        

  build-oss-docker-images:
    name: Build Cassandra images
    runs-on: macos-latest
    needs: run-unit-tests
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        cassandra-version: ['4.0', '4.1', '5.0']
        base-platform: ['ubuntu', 'ubi']
        exclude:
          - cassandra-version: '5.0'
            base-platform: 'ubuntu'
    steps:
      - name: Restore build workspace
        uses: actions/cache/restore@v5
        with:
          path: /home/runner/work/management-api-for-apache-cassandra/management-api-for-apache-cassandra
          key: ${{ runner.os }}-workspace-${{ github.sha }}-${{ hashFiles('**/pom.xml') }}
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ github.sha }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Setup metadata based on the commit/tag that will be used for tagging the image
      # Only build and publish a commit based tag
      - name: Setup Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: k8ssandra/cass-management-api
          tags: type=sha,format=long,prefix=${{ matrix.cassandra-version }}-${{ matrix.base-platform }}-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Cassandra ${{ matrix.cassandra-version }}-${{ matrix.base-platform }}
        if: ${{ matrix.base-platform == 'ubuntu' }}
        id: docker_build_ubuntu
        uses: docker/build-push-action@v7
        with:
          file: cassandra/Dockerfile-${{ matrix.cassandra-version }}
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64
          target: cassandra
          outputs: type=docker,dest=/tmp/cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}.tar
      - name: Build Cassandra ${{ matrix.cassandra-version }}-${{ matrix.base-platform }}
        if: ${{ matrix.base-platform != 'ubuntu' }}
        id: docker_build_ubi
        uses: docker/build-push-action@v7
        with:
          file: cassandra/Dockerfile-${{ matrix.cassandra-version }}.${{ matrix.base-platform }}
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64
          target: cassandra
          outputs: type=docker,dest=/tmp/cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}.tar
      - name: Upload Docker Image for Cassandra ${{ matrix.cassandra-version }}-${{ matrix.base-platform }}
        uses: actions/upload-artifact@v7
        with:
          name: cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}
          path: /tmp/cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}.tar
          retention-days: 3

  test-oss:
    name: Run Cassandra ${{ matrix.itTest }} [${{ matrix.cassandra-version }}, ${{ matrix.base-platform }}]
    needs: build-oss-docker-images
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        cassandra-version: ['4.0', '4.1', '5.0']
        base-platform: ['ubuntu', 'ubi']
        itTest : ['LifecycleIT', 'KeepAliveIT', 'NonDestructiveOpsIT', 'DestructiveOpsIT', 'NonDestructiveOpsResourcesV2IT', 'DockerImageIT', 'AsyncRepairIT', 'PortOverrideIT', 'MetricsIT']
        exclude:
          - cassandra-version: '5.0'
            base-platform: 'ubuntu'
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ github.sha }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Restore Cassandra Download for tests
        uses: actions/cache/restore@v5
        with:
          path: /home/runner/work/management-api-for-apache-cassandra/management-api-for-apache-cassandra/management-api-server/.cassandra-bin
          key: cassandra-download-${{ github.sha }}
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}
          path: /tmp
      - name: Load Docker ${{ matrix.cassandra-version }}-${{ matrix.base-platform }} image
        if: ${{ matrix.base-platform == 'ubuntu' }}
        run: |
          docker load --input /tmp/cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}.tar
          docker tag k8ssandra/cass-management-api:${{ matrix.cassandra-version }}-${{ matrix.base-platform }}-${{ github.sha }} mgmtapi-dockerfile-${{ matrix.cassandra-version }}-test:latest
          docker image ls -a
      - name: Load Docker ${{ matrix.cassandra-version }}-${{ matrix.base-platform }} image
        if: ${{ matrix.base-platform != 'ubuntu' }}
        run: |
          docker load --input /tmp/cassandra.${{ matrix.cassandra-version }}.${{ matrix.base-platform }}.tar
          docker tag k8ssandra/cass-management-api:${{ matrix.cassandra-version }}-${{ matrix.base-platform }}-${{ github.sha }} mgmtapi-dockerfile-${{ matrix.cassandra-version }}.${{ matrix.base-platform }}-test:latest
          docker image ls -a
      - name: Build with Maven and run tests
        if: ${{ matrix.base-platform == 'ubuntu' }}
        run: |
          mvn -B -q verify -Dskip.surefire.tests --file pom.xml \
          -Drun${{ matrix.cassandra-version }}tests \
          -Dit.test=${{ matrix.itTest }} -DfailIfNoTests=false
      - name: Build with Maven and run tests
        if: ${{ matrix.base-platform != 'ubuntu' }}
        run: |
          mvn -B -q verify -Dskip.surefire.tests --file pom.xml \
          -Drun${{ matrix.cassandra-version }}testsUBI \
          -Dit.test=${{ matrix.itTest }} -DfailIfNoTests=false